# Generated by Django 3.2.2 on 2021-05-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="cep",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="person",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
