# Generated by Django 3.2.2 on 2021-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20210508_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="update_in",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
